spring.application.name=rabbitmq-streams

# logging
logging.level.root=info
logging.level.org.mongodb.driver=error
logging.level.org.springframework.data.mongodb.core.MongoTemplate=error
spring.output.ansi.enabled=always

# rabbitmq (stream)
spring.rabbitmq.stream.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.stream.port=${RABBITMQ_STREAM_PORT:5552}
spring.rabbitmq.stream.password=${RABBITMQ_PASSWORD:root}
spring.rabbitmq.stream.username=${RABBITMQ_USERNAME:root}

# rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:root}
spring.rabbitmq.username=${RABBITMQ_USERNAME:root}

# database
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=${DB_URI:mongodb://root:root@localhost:27017/streams_mvp}