spring.application.name=aftersale

#spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
#spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
#spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:root}
#spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:root}
#
#spring.rabbitmq.listener.simple.concurrency=1
#spring.rabbitmq.listener.simple.max-concurrency=1
#spring.rabbitmq.listener.simple.prefetch=1


# Order/OMS (connection)
rabbitmq.settings.connections[0].name=OMS
rabbitmq.settings.connections[0].host=${RABBITMQ_ORDER_HOST:rabbitmq}
rabbitmq.settings.connections[0].port=${RABBITMQ_ORDER_PORT:5672}
rabbitmq.settings.connections[0].username=${RABBITMQ_ORDER_USERNAME:root}
rabbitmq.settings.connections[0].password=${RABBITMQ_ORDER_PASSWORD:root}
rabbitmq.settings.connections[0].virtual-host=${RABBITMQ_ORDER_VIRTUAL_HOST:/order}
rabbitmq.settings.connections[0].ssl-settings.enabled=${RABBITMQ_ENABLE_SSL:false}
rabbitmq.settings.connections[0].ssl-settings.algorithm=TLSv1.2
rabbitmq.settings.connections[0].listener-settings.default-requeue-rejected=false
rabbitmq.settings.connections[0].listener-settings.concurrent-consumers=3
rabbitmq.settings.connections[0].listener-settings.prefetch=50

# Tracking (connection)
rabbitmq.settings.connections[1].name=TRACKING
rabbitmq.settings.connections[1].host=${RABBITMQ_TRACKING_HOST:rabbitmq}
rabbitmq.settings.connections[1].port=${RABBITMQ_TRACKING_PORT:5672}
rabbitmq.settings.connections[1].username=${RABBITMQ_TRACKING_USERNAME:root}
rabbitmq.settings.connections[1].password=${RABBITMQ_TRACKING_PASSWORD:root}
rabbitmq.settings.connections[1].virtual-host=${RABBITMQ_TRACKING_VIRTUAL_HOST:/tracking}
rabbitmq.settings.connections[1].ssl-settings.enabled=${RABBITMQ_ENABLE_SSL:false}
rabbitmq.settings.connections[1].ssl-settings.algorithm=TLSv1.2
rabbitmq.settings.connections[1].listener-settings.default-requeue-rejected=false
rabbitmq.settings.connections[1].listener-settings.concurrent-consumers=3
rabbitmq.settings.connections[1].listener-settings.prefetch=50

# TMS (connection)
rabbitmq.settings.connections[2].name=TMS
rabbitmq.settings.connections[2].host=${RABBITMQ_TMS_HOST:rabbitmq}
rabbitmq.settings.connections[2].port=${RABBITMQ_TMS_PORT:5672}
rabbitmq.settings.connections[2].username=${RABBITMQ_TMS_USERNAME:root}
rabbitmq.settings.connections[2].password=${RABBITMQ_TMS_PASSWORD:root}
rabbitmq.settings.connections[2].virtual-host=${RABBITMQ_TMS_VIRTUAL_HOST:/tms}
rabbitmq.settings.connections[2].ssl-settings.enabled=${RABBITMQ_ENABLE_SSL:false}
rabbitmq.settings.connections[2].ssl-settings.algorithm=TLSv1.2
rabbitmq.settings.connections[2].listener-settings.default-requeue-rejected=false
rabbitmq.settings.connections[2].listener-settings.concurrent-consumers=3
rabbitmq.settings.connections[2].listener-settings.prefetch=50