spring.application.name=kafka-streams

# logging
logging.level.com.github.throyer=debug
logging.level.root=info
logging.level.org.mongodb.driver=error
logging.level.org.springframework.data.mongodb.core.MongoTemplate=error
spring.output.ansi.enabled=always

# kafka
kafka.bootstrap-servers=kafka:9092
kafka.topic=order-events
kafka.group-id=after-sale-processors

# database
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${DB_URI:mongodb://root:root@localhost:27017/streams_mvp}