spring.application.name=rabbitmq-streams

# logging
logging.level.root=info
logging.level.org.mongodb.driver=error
logging.level.org.springframework.data.mongodb.core.MongoTemplate=error
spring.output.ansi.enabled=always

# rabbitmq (stream)
spring.rabbitmq.stream.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.stream.port=${RABBITMQ_STREAM_PORT:5552}
spring.rabbitmq.stream.password=${RABBITMQ_PASSWORD:root}
spring.rabbitmq.stream.username=${RABBITMQ_USERNAME:root}

spring.cloud.stream.rabbit.bindings.pedidos-in-0.consumer.container-type=STREAM
spring.cloud.stream.rabbit.bindings.pedidos-in-0.consumer.super-stream=true

spring.cloud.stream.rabbit.bindings.pedidos-out-0.producer.super-stream=true

spring.cloud.stream.bindings.pedidos-in-0.destination=events
spring.cloud.stream.bindings.pedidos-in-0.group=events_processor
spring.cloud.stream.bindings.pedidos-in-0.consumer.instance-count=3
spring.cloud.stream.bindings.pedidos-in-0.consumer.concurrency=3

spring.cloud.stream.bindings.pedidos-out-0.destination=events
spring.cloud.stream.bindings.pedidos-out-0.producer.partition-count=3
spring.cloud.stream.bindings.pedidos-out-0.producer.partition-key-expression=payload.id
# spring.cloud.stream.bindings.pedidos-out-0.producer.auto-startup=true



# rabbitmq super stream
# rabbitmq.stream.name=events.stream
# rabbitmq.stream.partitions=2
# rabbitmq.stream.consumer.group=events-processor

# rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:root}
spring.rabbitmq.username=${RABBITMQ_USERNAME:root}

# database
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=${DB_URI:mongodb://root:root@localhost:27017/streams_mvp}