events {
    worker_connections 1000;
}

http {
    access_log off;
    sendfile   on;
    
    upstream api {
        server producer01:8080;
        server producer02:8080;
        server producer03:8080;
        server producer04:8080;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://api;
        }
    }
}