x-producer-service: &producer-service
  build:
    context: ../producer
    dockerfile: ../.docker/Dockerfile.prod
  expose:
    - 8080
  environment:
    TZ: "${TIMEZONE}"
    SERVER_PORT: 8080
  env_file:
    - ".env"
  links:
    - rabbitmq
  deploy:
    resources:
      limits:
        cpus: "0.50"
        memory: "300MB"
  entrypoint: [
    "java",
    "-jar",
    "api.jar"
  ]
        
x-consumer-service: &consumer-service
  build:
    context: ../consumer
    dockerfile: ../.docker/Dockerfile.prod
  environment:
    TZ: "${TIMEZONE}"
    SERVER_PORT: 8080
  env_file:
    - ".env"
  links:
    - rabbitmq
    - database
  deploy:
    resources:
      limits:
        cpus: "0.60"
        memory: "250MB"
  entrypoint: [
    "java",
    "-jar",
    "api.jar"
  ]
        
services:
  producer_01:
    <<: *producer-service
    container_name: producer-01
    hostname: producer01
    
  producer_02:
    <<: *producer-service
    container_name: producer-02
    hostname: producer02
    
  producer_03:
    <<: *producer-service
    container_name: producer-03
    hostname: producer03
    
  producer_04:
    <<: *producer-service
    container_name: producer-04
    hostname: producer04
  
  consumer_01:
    <<: *consumer-service
    container_name: consumer-01
    hostname: consumer01
    
  consumer_02:
    <<: *consumer-service
    container_name: consumer-02
    hostname: consumer02

  consumer_03:
    <<: *consumer-service
    container_name: consumer-03
    hostname: consumer03

  consumer_04:
    <<: *consumer-service
    container_name: consumer-04
    hostname: consumer04
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - producer_01
      - producer_02
      - producer_03
      - producer_04 
    depends_on:
      - producer_01
      - producer_02
      - producer_03
      - producer_04
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
    
  database:
    container_name: database
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${DB_PORT}:27017"
    environment:
      TZ: "${TIMEZONE}"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_DATABASE: root_database
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/.volumes/throyer/pocs/rabbitmq-streams/mongodb:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "270MB"

  rabbitmq:
    image: rabbitmq:3.13.7-management
    restart: unless-stopped
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_STREAM_PORT}:5552"
      - "${RABBITMQ_CLIENT_WEB_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "270MB"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://app-connect:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
  maven:
networks:
  default:
    driver: bridge
    name: poc