FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /app

COPY ./pom.xml ./pom.xml
COPY ./src ./src

RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

FROM eclipse-temurin:17-jdk-noble

WORKDIR /app

ENV SERVER_PORT=80
ENV DOCKERIZE_VERSION=v0.9.9

COPY --from=BUILDER /app/target/*.jar ./api.jar

RUN apt-get update \
    && apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

EXPOSE ${SERVER_PORT}

ENTRYPOINT [ "java", "-jar", "api.jar" ]