services:
  service:
    image: throyer/poc/rabbitmq-streams
    container_name: server
    ports:
      - "8080:8080"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    expose:
      - 8080
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    environment:
      TZ: "${TIMEZONE}"
    env_file:
      - ".env"
    volumes:
      - ../:/app
      - maven:/root/.m2/repository
    links:
      - database
      - rabbitmq
    
  database:
    container_name: database
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${DB_PORT}:27017"
    environment:
      TZ: "${TIMEZONE}"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_DATABASE: root_database
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/.volumes/throyer/pocs/rabbitmq-streams/mongodb:/data/db

  rabbitmq:
    image: rabbitmq:3.13.7-management
    restart: unless-stopped
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_STREAM_PORT}:5552"
      - "${RABBITMQ_CLIENT_WEB_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    tty: true

volumes:
  maven: