FROM maven:3.9.9-eclipse-temurin-17-alpine AS builder

WORKDIR /app

COPY ./pom.xml ./pom.xml
COPY ./src ./src

RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

FROM eclipse-temurin:17-alpine

WORKDIR /app

ENV SERVER_PORT=80
ENV DOCKERIZE_VERSION=v0.9.9

COPY --from=BUILDER /app/target/*.jar ./api.jar

RUN apk add --no-cache openssl

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

EXPOSE ${SERVER_PORT}

ENTRYPOINT [ "java", "-jar", "api.jar" ]